build: 
		javac PreparedStatementCustom.java Main.java Database.java Artist.java Album.java AlbumDAO.java ArtistDAO.java AlbumController.java ArtistController.java Chart.java ChartController.java ChartDAO.java -d .

run: 
	java -classpath ".:libs/mysql-connector-java-5.1.48.jar:libs/automaton-1.11-8.jar:libs/commons-lang3-3.5.jar:libs/generex-1.0.2.jar:libs/javafaker-0.12.jar:libs/mysql-connector-java-5.1.48.jar:." lab8/Main
