build: 
		javac PreparedStatementCustom.java Main.java Database.java Artist.java Album.java AlbumDAO.java ArtistDAO.java AlbumController.java ArtistController.java -d .

run: 
	java -classpath ".:libs/mysql-connector-java-5.1.48.jar:." lab8/Main
